### ISSUE TITLE
[JOSS] Review comments

### ISSUE THREAD

**Issue by DanielVandH** [smillerc/CurvilinearGrids.jl#24]
Hi @smillerc,

This is for https://github.com/openjournals/joss-reviews/issues/7508. 

The paper is nicely written and your code has a nice structure, and gives a nice contribution for the Julia ecosystem. I just have some comments:

- The README should explain how to install the package (essentially, just something like `using Pkg; Pkg.add("CurvilinearGrids"); using CurvilinearGrids`).
- You use the terminology "halo" in the README and in the code example in the paper, but that's not clearly defined anywhere.
- The paper is missing a statement of need. At present, it is not immediately obvious to the reader (1) why this work is useful and (2) what gap it fills compared to other software in this area. It would improve the work to know how it compares to this other software.
- While I can roughly understand how to make use of the package from the README examples, I think it might help to also include an example where you are actually applying the package to another applied problem, which would also really showcase how the API can be used. 
- The API describes `coord`, `centroid`, `coords`, and `centroids`, but you should also document the `CurvilinearGrid` functions.
- Your CI is only testing 1.9 and nightly. You should change it to test `1`, `lts`, and `pre` (or, at least, `1` so that it tests the latest release). I confirmed locally that it passes on 1.11 but it should be included in the CI.
- The definition of the Jacobian is given at the very end but maybe it'd be useful to explain it more concisely sooner since you make use of it already.

Some other minor things:

- Line 22: "Figure Figure 1"

**Comment by smillerc** [comment]
@DanielVandH I've made changes to the paper as well as the README and internal docstrings. Thank you for your edits!

**Comment by DanielVandH** [comment]
Thanks @smillerc, I'll take another look soon!

**Comment by smillerc** [comment]
@DanielVandH I've made the changes you requested. Check out the latest changes on master (new release) in the manuscript. Thanks!

**Comment by DanielVandH** [comment]
Thanks @smillerc. Can you point out what the changes were for the first two points? i.e.

  1. Maybe to make it clearer where the statement of need ends, an extra section heading for the Examples could be useful
  2. The statement of need does make it clear now who and what the package is for, but it's still not as clear how it relates to existing software. You mention the state of the Julia ecosystem but are there similar things that could be referenced from other languages to compare the work with? By compare I don't necessarily mean whether one is better than the other but just in terms of what's implemented potentially (having this in a language like Julia is definitely a good bonus over other languages e.g. Python to begin with!). This would be especially useful for readers who might not know what Julia is.

I'm looking at https://github.com/openjournals/joss-reviews/issues/7508#issuecomment-2546349148 but don't see any change in e.g. the statement of need. Thanks.

**Comment by smillerc** [comment]
Oh wow, I'm surprised my code editor missed that. Thank you!
